services:
  backend:
    build:
      context: ../../../
      dockerfile: apps/backend/Dockerfile
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - INFISICAL_CLIENT_ID=${INFISICAL_CLIENT_ID}
      - INFISICAL_CLIENT_SECRET=${INFISICAL_CLIENT_SECRET}
    ports:
      - "${PORT}:3000"
    depends_on:
      db:
        condition: service_started

  db:
    build:
      context: mongo
      dockerfile: mongo.Dockerfile # The custom Mongo image we built
    restart: always
    environment:
      - INFISICAL_CLIENT_ID=${INFISICAL_CLIENT_ID}
      - INFISICAL_CLIENT_SECRET=${INFISICAL_CLIENT_SECRET}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  db-panel:
#    image: mongo-express # If you can't edit this, it still needs a way to get secrets
    build:
      context: mongo
      dockerfile: mongo-express.Dockerfile
    restart: always
    environment:
      - INFISICAL_CLIENT_ID=${INFISICAL_CLIENT_ID}
      - INFISICAL_CLIENT_SECRET=${INFISICAL_CLIENT_SECRET}
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    depends_on:
      - db

volumes:
  mongo_data: